# Generated by Django 6.0.2 on 2026-03-02 09:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('ORG_MANAGER', 'Organization Manager'), ('ORG_ADMIN', 'Organization Admin')], default='EMPLOYEE', max_length=20)),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identifier', max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='Employee phone number in format +998111111111', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998111111111'.", regex='^\\+998\\d{9}$')])),
                ('department', models.ForeignKey(blank=True, help_text="Employee's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('managed_organization', models.ForeignKey(blank=True, help_text='Organization this user administers (only for ADMINISTRATION role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='app.organization')),
                ('position', models.ForeignKey(blank=True, help_text="Employee's job position", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app.jobposition')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['employee_id'], name='users_user_employe_e638d5_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
