# Generated by Django 6.0.2 on 2026-03-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_employe_e638d5_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
    ]
