# Generated by Django 6.0.2 on 2026-03-02 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Manager/Head of this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='head_of_organization',
            field=models.ForeignKey(blank=True, help_text='Head / CEO of this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this department belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='app.organization'),
        ),
    ]
